spring:
  application:
    name: test_app

  hazelcast:
    config: classpath:/consumer/telemetry/hazelcast-client.xml
  cache:
    type: hazelcast

server:
  servlet-path: /
  port: 11000
  undertow:
    ioThreads: 4 #15
    workerThreads: 15 #150
    accesslog:
      enabled: true
  compression:
    enabled: true
    mimeTypes: text/xml, text/css, text/html, application/json
    minResponseSize: 4096


# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints
# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-actuator-with-jersey
endpoints:
  enabled: true
  info:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true

# app name and build version updated during build process from Maven properties.
info:
  app:
    name: Sample #@project.artifactId@
  build:
    version: '0.1' #@project.version@